config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :scrapping_api do
      namespace :v1 do
        namespace :scrapper do
          get 'get_list'
          post 'scrap'
        end
      end
    end
  end

end

app/models/scrapped_datum.rb
class ScrappedDatum < ActiveRecord::Base

	validates_presence_of :url

	def self.get_all
    	ScrappedDatum.all.as_json(except: [:created_at, :updated_at, :id])
  	end

end

app/controllers/api/scrapping_api/v1/scrapper_controller.rb
module Api::ScrappingApi::V1
	class ScrapperController < ApplicationController
		
		def get_list
			render json: {
				scrapped_data_list: ScrappedDatum.get_all.each{ |a| a['data'] = JSON.parse(a['data']) },
          		messages: ['Success']
          	},status: :ok and return
		end

		def scrap
			require 'open-uri'
			require 'uri'

			if params['scrapper']['url'].blank?
				render_json("Failed",['URL not found'],:bad_request) and return
			end

			if URI.parse(params['scrapper']['url']).host.nil?
				render_json("Failed",['Invalid URL'],:bad_request) and return
			end	

			content = Nokogiri::HTML(open(params['scrapper']['url']))
			
			obj = Hash.new
			obj = {h1: [], h2: [], h3: [], a: []}
			obj.each do |key,val|
				content.css(key).each do |elem,index| 
					obj[key].push(elem.text.strip) unless elem.text.blank?
				end
			end

			@scrapped_data = ScrappedDatum.new
			@scrapped_data.url = params['scrapper']['url']
			@scrapped_data.data = obj.to_json

			if @scrapped_data.valid?
				@scrapped_data.save!
			else
				render_json("Failed",["The result does not save due to errors. Please try again."],:bad_request) and return	
			end	
			
			render_json("Success",['Data scrapped from given url'],:ok) and return
			
		end	
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

    def render_json(response, message, status_code)
    	render json: {result: response, messages: message}, status: status_code
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scrapper_helper.rb
module ScrapperHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crawler</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/scrapper/index.html.erb
<h1>Hello World</h1>


<%= form_for :scrapper, url: scrapper_scrap_path do |f| %>
  <p>
    <%= f.label :URL %><br>
    <%= f.text_field :url %>
  </p>
 
  <p>
    <%= f.submit :'Start Scrapping' %>
  </p>
<% end %>